/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SportsSportIdRouteImport } from './routes/sports.$sportId'
import { Route as PagesTrainingRouteImport } from './routes/pages/training'
import { Route as PagesSportsRouteImport } from './routes/pages/sports'
import { Route as PagesPerformanceRouteImport } from './routes/pages/performance'
import { Route as PagesHealthRouteImport } from './routes/pages/health'
import { Route as PagesFacilitiesRouteImport } from './routes/pages/facilities'
import { Route as PagesEventsRouteImport } from './routes/pages/events'
import { Route as PagesAthletesRouteImport } from './routes/pages/athletes'
import { Route as PagesReportsRouteRouteImport } from './routes/pages/reports/route'
import { Route as PagesCoachesRouteRouteImport } from './routes/pages/coaches/route'
import { Route as PagesReportsIndexRouteImport } from './routes/pages/reports/index'
import { Route as PagesReportsPlayersRouteImport } from './routes/pages/reports/players'
import { Route as PagesReportsCoachesRouteImport } from './routes/pages/reports/coaches'
import { Route as PagesCoachesPerformanceRouteImport } from './routes/pages/coaches/performance'
import { Route as PagesCoachesOverviewsRouteImport } from './routes/pages/coaches/overviews'
import { Route as PagesCoachesDirectoryRouteImport } from './routes/pages/coaches/directory'
import { Route as PagesCoachesCertificationsRouteImport } from './routes/pages/coaches/certifications'
import { Route as PagesCoachesAssignmentsRouteImport } from './routes/pages/coaches/assignments'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIdRoute = SportsSportIdRouteImport.update({
  id: '/$sportId',
  path: '/$sportId',
  getParentRoute: () => SportsRoute,
} as any)
const PagesTrainingRoute = PagesTrainingRouteImport.update({
  id: '/pages/training',
  path: '/pages/training',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSportsRoute = PagesSportsRouteImport.update({
  id: '/pages/sports',
  path: '/pages/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPerformanceRoute = PagesPerformanceRouteImport.update({
  id: '/pages/performance',
  path: '/pages/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHealthRoute = PagesHealthRouteImport.update({
  id: '/pages/health',
  path: '/pages/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesFacilitiesRoute = PagesFacilitiesRouteImport.update({
  id: '/pages/facilities',
  path: '/pages/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesEventsRoute = PagesEventsRouteImport.update({
  id: '/pages/events',
  path: '/pages/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAthletesRoute = PagesAthletesRouteImport.update({
  id: '/pages/athletes',
  path: '/pages/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReportsRouteRoute = PagesReportsRouteRouteImport.update({
  id: '/pages/reports',
  path: '/pages/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCoachesRouteRoute = PagesCoachesRouteRouteImport.update({
  id: '/pages/coaches',
  path: '/pages/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReportsIndexRoute = PagesReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesReportsRouteRoute,
} as any)
const PagesReportsPlayersRoute = PagesReportsPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => PagesReportsRouteRoute,
} as any)
const PagesReportsCoachesRoute = PagesReportsCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => PagesReportsRouteRoute,
} as any)
const PagesCoachesPerformanceRoute = PagesCoachesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PagesCoachesRouteRoute,
} as any)
const PagesCoachesOverviewsRoute = PagesCoachesOverviewsRouteImport.update({
  id: '/overviews',
  path: '/overviews',
  getParentRoute: () => PagesCoachesRouteRoute,
} as any)
const PagesCoachesDirectoryRoute = PagesCoachesDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => PagesCoachesRouteRoute,
} as any)
const PagesCoachesCertificationsRoute =
  PagesCoachesCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => PagesCoachesRouteRoute,
  } as any)
const PagesCoachesAssignmentsRoute = PagesCoachesAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => PagesCoachesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/users': typeof UsersRoute
  '/pages/coaches': typeof PagesCoachesRouteRouteWithChildren
  '/pages/reports': typeof PagesReportsRouteRouteWithChildren
  '/pages/athletes': typeof PagesAthletesRoute
  '/pages/events': typeof PagesEventsRoute
  '/pages/facilities': typeof PagesFacilitiesRoute
  '/pages/health': typeof PagesHealthRoute
  '/pages/performance': typeof PagesPerformanceRoute
  '/pages/sports': typeof PagesSportsRoute
  '/pages/training': typeof PagesTrainingRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/pages/coaches/assignments': typeof PagesCoachesAssignmentsRoute
  '/pages/coaches/certifications': typeof PagesCoachesCertificationsRoute
  '/pages/coaches/directory': typeof PagesCoachesDirectoryRoute
  '/pages/coaches/overviews': typeof PagesCoachesOverviewsRoute
  '/pages/coaches/performance': typeof PagesCoachesPerformanceRoute
  '/pages/reports/coaches': typeof PagesReportsCoachesRoute
  '/pages/reports/players': typeof PagesReportsPlayersRoute
  '/pages/reports/': typeof PagesReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/users': typeof UsersRoute
  '/pages/coaches': typeof PagesCoachesRouteRouteWithChildren
  '/pages/athletes': typeof PagesAthletesRoute
  '/pages/events': typeof PagesEventsRoute
  '/pages/facilities': typeof PagesFacilitiesRoute
  '/pages/health': typeof PagesHealthRoute
  '/pages/performance': typeof PagesPerformanceRoute
  '/pages/sports': typeof PagesSportsRoute
  '/pages/training': typeof PagesTrainingRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/pages/coaches/assignments': typeof PagesCoachesAssignmentsRoute
  '/pages/coaches/certifications': typeof PagesCoachesCertificationsRoute
  '/pages/coaches/directory': typeof PagesCoachesDirectoryRoute
  '/pages/coaches/overviews': typeof PagesCoachesOverviewsRoute
  '/pages/coaches/performance': typeof PagesCoachesPerformanceRoute
  '/pages/reports/coaches': typeof PagesReportsCoachesRoute
  '/pages/reports/players': typeof PagesReportsPlayersRoute
  '/pages/reports': typeof PagesReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sports': typeof SportsRouteWithChildren
  '/users': typeof UsersRoute
  '/pages/coaches': typeof PagesCoachesRouteRouteWithChildren
  '/pages/reports': typeof PagesReportsRouteRouteWithChildren
  '/pages/athletes': typeof PagesAthletesRoute
  '/pages/events': typeof PagesEventsRoute
  '/pages/facilities': typeof PagesFacilitiesRoute
  '/pages/health': typeof PagesHealthRoute
  '/pages/performance': typeof PagesPerformanceRoute
  '/pages/sports': typeof PagesSportsRoute
  '/pages/training': typeof PagesTrainingRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/pages/coaches/assignments': typeof PagesCoachesAssignmentsRoute
  '/pages/coaches/certifications': typeof PagesCoachesCertificationsRoute
  '/pages/coaches/directory': typeof PagesCoachesDirectoryRoute
  '/pages/coaches/overviews': typeof PagesCoachesOverviewsRoute
  '/pages/coaches/performance': typeof PagesCoachesPerformanceRoute
  '/pages/reports/coaches': typeof PagesReportsCoachesRoute
  '/pages/reports/players': typeof PagesReportsPlayersRoute
  '/pages/reports/': typeof PagesReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/users'
    | '/pages/coaches'
    | '/pages/reports'
    | '/pages/athletes'
    | '/pages/events'
    | '/pages/facilities'
    | '/pages/health'
    | '/pages/performance'
    | '/pages/sports'
    | '/pages/training'
    | '/sports/$sportId'
    | '/pages/coaches/assignments'
    | '/pages/coaches/certifications'
    | '/pages/coaches/directory'
    | '/pages/coaches/overviews'
    | '/pages/coaches/performance'
    | '/pages/reports/coaches'
    | '/pages/reports/players'
    | '/pages/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/users'
    | '/pages/coaches'
    | '/pages/athletes'
    | '/pages/events'
    | '/pages/facilities'
    | '/pages/health'
    | '/pages/performance'
    | '/pages/sports'
    | '/pages/training'
    | '/sports/$sportId'
    | '/pages/coaches/assignments'
    | '/pages/coaches/certifications'
    | '/pages/coaches/directory'
    | '/pages/coaches/overviews'
    | '/pages/coaches/performance'
    | '/pages/reports/coaches'
    | '/pages/reports/players'
    | '/pages/reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sports'
    | '/users'
    | '/pages/coaches'
    | '/pages/reports'
    | '/pages/athletes'
    | '/pages/events'
    | '/pages/facilities'
    | '/pages/health'
    | '/pages/performance'
    | '/pages/sports'
    | '/pages/training'
    | '/sports/$sportId'
    | '/pages/coaches/assignments'
    | '/pages/coaches/certifications'
    | '/pages/coaches/directory'
    | '/pages/coaches/overviews'
    | '/pages/coaches/performance'
    | '/pages/reports/coaches'
    | '/pages/reports/players'
    | '/pages/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SportsRoute: typeof SportsRouteWithChildren
  UsersRoute: typeof UsersRoute
  PagesCoachesRouteRoute: typeof PagesCoachesRouteRouteWithChildren
  PagesReportsRouteRoute: typeof PagesReportsRouteRouteWithChildren
  PagesAthletesRoute: typeof PagesAthletesRoute
  PagesEventsRoute: typeof PagesEventsRoute
  PagesFacilitiesRoute: typeof PagesFacilitiesRoute
  PagesHealthRoute: typeof PagesHealthRoute
  PagesPerformanceRoute: typeof PagesPerformanceRoute
  PagesSportsRoute: typeof PagesSportsRoute
  PagesTrainingRoute: typeof PagesTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportId': {
      id: '/sports/$sportId'
      path: '/$sportId'
      fullPath: '/sports/$sportId'
      preLoaderRoute: typeof SportsSportIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/pages/training': {
      id: '/pages/training'
      path: '/pages/training'
      fullPath: '/pages/training'
      preLoaderRoute: typeof PagesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/sports': {
      id: '/pages/sports'
      path: '/pages/sports'
      fullPath: '/pages/sports'
      preLoaderRoute: typeof PagesSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/performance': {
      id: '/pages/performance'
      path: '/pages/performance'
      fullPath: '/pages/performance'
      preLoaderRoute: typeof PagesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/health': {
      id: '/pages/health'
      path: '/pages/health'
      fullPath: '/pages/health'
      preLoaderRoute: typeof PagesHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/facilities': {
      id: '/pages/facilities'
      path: '/pages/facilities'
      fullPath: '/pages/facilities'
      preLoaderRoute: typeof PagesFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/events': {
      id: '/pages/events'
      path: '/pages/events'
      fullPath: '/pages/events'
      preLoaderRoute: typeof PagesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/athletes': {
      id: '/pages/athletes'
      path: '/pages/athletes'
      fullPath: '/pages/athletes'
      preLoaderRoute: typeof PagesAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/reports': {
      id: '/pages/reports'
      path: '/pages/reports'
      fullPath: '/pages/reports'
      preLoaderRoute: typeof PagesReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/coaches': {
      id: '/pages/coaches'
      path: '/pages/coaches'
      fullPath: '/pages/coaches'
      preLoaderRoute: typeof PagesCoachesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/reports/': {
      id: '/pages/reports/'
      path: '/'
      fullPath: '/pages/reports/'
      preLoaderRoute: typeof PagesReportsIndexRouteImport
      parentRoute: typeof PagesReportsRouteRoute
    }
    '/pages/reports/players': {
      id: '/pages/reports/players'
      path: '/players'
      fullPath: '/pages/reports/players'
      preLoaderRoute: typeof PagesReportsPlayersRouteImport
      parentRoute: typeof PagesReportsRouteRoute
    }
    '/pages/reports/coaches': {
      id: '/pages/reports/coaches'
      path: '/coaches'
      fullPath: '/pages/reports/coaches'
      preLoaderRoute: typeof PagesReportsCoachesRouteImport
      parentRoute: typeof PagesReportsRouteRoute
    }
    '/pages/coaches/performance': {
      id: '/pages/coaches/performance'
      path: '/performance'
      fullPath: '/pages/coaches/performance'
      preLoaderRoute: typeof PagesCoachesPerformanceRouteImport
      parentRoute: typeof PagesCoachesRouteRoute
    }
    '/pages/coaches/overviews': {
      id: '/pages/coaches/overviews'
      path: '/overviews'
      fullPath: '/pages/coaches/overviews'
      preLoaderRoute: typeof PagesCoachesOverviewsRouteImport
      parentRoute: typeof PagesCoachesRouteRoute
    }
    '/pages/coaches/directory': {
      id: '/pages/coaches/directory'
      path: '/directory'
      fullPath: '/pages/coaches/directory'
      preLoaderRoute: typeof PagesCoachesDirectoryRouteImport
      parentRoute: typeof PagesCoachesRouteRoute
    }
    '/pages/coaches/certifications': {
      id: '/pages/coaches/certifications'
      path: '/certifications'
      fullPath: '/pages/coaches/certifications'
      preLoaderRoute: typeof PagesCoachesCertificationsRouteImport
      parentRoute: typeof PagesCoachesRouteRoute
    }
    '/pages/coaches/assignments': {
      id: '/pages/coaches/assignments'
      path: '/assignments'
      fullPath: '/pages/coaches/assignments'
      preLoaderRoute: typeof PagesCoachesAssignmentsRouteImport
      parentRoute: typeof PagesCoachesRouteRoute
    }
  }
}

interface SportsRouteChildren {
  SportsSportIdRoute: typeof SportsSportIdRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportIdRoute: SportsSportIdRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface PagesCoachesRouteRouteChildren {
  PagesCoachesAssignmentsRoute: typeof PagesCoachesAssignmentsRoute
  PagesCoachesCertificationsRoute: typeof PagesCoachesCertificationsRoute
  PagesCoachesDirectoryRoute: typeof PagesCoachesDirectoryRoute
  PagesCoachesOverviewsRoute: typeof PagesCoachesOverviewsRoute
  PagesCoachesPerformanceRoute: typeof PagesCoachesPerformanceRoute
}

const PagesCoachesRouteRouteChildren: PagesCoachesRouteRouteChildren = {
  PagesCoachesAssignmentsRoute: PagesCoachesAssignmentsRoute,
  PagesCoachesCertificationsRoute: PagesCoachesCertificationsRoute,
  PagesCoachesDirectoryRoute: PagesCoachesDirectoryRoute,
  PagesCoachesOverviewsRoute: PagesCoachesOverviewsRoute,
  PagesCoachesPerformanceRoute: PagesCoachesPerformanceRoute,
}

const PagesCoachesRouteRouteWithChildren =
  PagesCoachesRouteRoute._addFileChildren(PagesCoachesRouteRouteChildren)

interface PagesReportsRouteRouteChildren {
  PagesReportsCoachesRoute: typeof PagesReportsCoachesRoute
  PagesReportsPlayersRoute: typeof PagesReportsPlayersRoute
  PagesReportsIndexRoute: typeof PagesReportsIndexRoute
}

const PagesReportsRouteRouteChildren: PagesReportsRouteRouteChildren = {
  PagesReportsCoachesRoute: PagesReportsCoachesRoute,
  PagesReportsPlayersRoute: PagesReportsPlayersRoute,
  PagesReportsIndexRoute: PagesReportsIndexRoute,
}

const PagesReportsRouteRouteWithChildren =
  PagesReportsRouteRoute._addFileChildren(PagesReportsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SportsRoute: SportsRouteWithChildren,
  UsersRoute: UsersRoute,
  PagesCoachesRouteRoute: PagesCoachesRouteRouteWithChildren,
  PagesReportsRouteRoute: PagesReportsRouteRouteWithChildren,
  PagesAthletesRoute: PagesAthletesRoute,
  PagesEventsRoute: PagesEventsRoute,
  PagesFacilitiesRoute: PagesFacilitiesRoute,
  PagesHealthRoute: PagesHealthRoute,
  PagesPerformanceRoute: PagesPerformanceRoute,
  PagesSportsRoute: PagesSportsRoute,
  PagesTrainingRoute: PagesTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
